### ISSUE TITLE
BUG: No incoming call warnings

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Dialer#1]
Hello, I am wondering about one thing. When i calling with someone and someone other try to call me, i get the SMS of lost incoming call. I use the "Right Dialer" some two weeks and as i remember i did not note incoming call while i had a phone call. I did not hear any incoming call warining, instead, i received many times the SMS announcing me of the incoming call.  So is "Right Dialer" capable to warn me of incoming call and switch to this other incoming call, please? This feature is really important for the dialer app!

**Comment by Goodwy** [comment]
This feature is implemented. Checked it again, it works.
Perhaps you have a device with two SIM cards and when you talk on one SIM card, the second becomes unavailable, because usually devices have only one module for calls.
