### ISSUE TITLE
Black backround colour as the default one (Dialer, Contacts & SMS) 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Dialer#12]
Hello, 

this "issue" holds for all Goodwy "Right" apps, esp. Dialer, Contacts and SMS. 

Can you set up deep black colour as the basic background colour of any "Right" apps (instead of the white one)? Or can you unlock this setting with primitive/limited "black vs. white" option and move it to the normal settings which is accessible for every user? 

This will be really appreciated for people they do not use/do not have GooglePlay on their phones. 

Thank you!

**Comment by Goodwy** [comment]
If your version of Android supports changing themes, it is enough to switch the system setting to dark mode and the app will also turn on the dark mode.
In the future I plan to unlock all functions for users who do not have Google Services.
