### ISSUE TITLE
BUG: black screen during incomming calls 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Dialer#14]
Hello, since some time - since some update - happening to me that when I have the incomming call, the screen is black (it is active, so not completely switched off, but black). It does not occur pernamently, just sometimes, but it is definitely annoying. I have to push the phone's hardware button to activate the screen and many times I miss the volume button and I switch off the screen completely with the power button. 

Can you examine this and fix it, please? 

Thank you. 

p.s.: LineageOS 16.0

**Comment by Moostek** [comment]
The problem is that this black screen during incomming call occurs irregulary, only sometimes. It will be hard to make a screenshot. 

I will try to describe: Sometimes during incomming calls the phone/screen is woke up, but without incomming call options (i.e. without Right Dialer incomming screen). I can see only Status Bar icons and "active" black background, that's all. The only solution I found is to tap on the Power button to lock the screen and then tap on the Power button again, to wake it up. After this I can see the incomming call options. 

And there is one more thing. I use the black skin, but the incomming call screen backround colour is grey. In one moment it turn from black to this grey background colour.

**Comment by Goodwy** [comment]
Does this problem exist in the latest versions of 5.0.0+?

**Comment by Moostek** [comment]
No, the problem did disappear. I do not face the issue with version 5.0.0+.
