### ISSUE TITLE
Missing dot on app's icon 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Dialer#15]
Hello, 

there is missing dot on app's icon while I have a missing call. All other apps on my phone they have this dot. So it will nice to fix it, please. 

Thank you. 

p.s.: LineageOS 16.0

**Comment by Goodwy** [comment]
This dot is displayed when there is a notification from the application. You can turn on missed call notifications in the settings, but two missed call notifications may be displayed, from this application and from the system dialer. If you can disable the system notification, it should work correctly.

**Comment by Clav12** [comment]
@Goodwy the option to turn on missed call notifications works great, you'd need to find a way to turn off system notifications so you don't have two,maybe delete the old code for missed call notifications.
I also wanted to ask you if you could kindly do a PR on simple dialer to implement this feature there too

**Comment by Goodwy** [comment]
The second missed notification is triggered by the system call application. I haven't found a way to disable it properly yet. Of course I can delete this notification, but for this I need full access to the notification, I would not like to request it.
