### ISSUE TITLE
BUG: Automatic rotation malfunction 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Dialer#19]
Hello, the Right Dialer app does not work with automatic rotation of my phone (LineageOS 16). Simply, no reaction, unlike to Right Messages app which works with automatic rotation function. Fix it, please. Thank you.

**Comment by Goodwy** [comment]
Hello, this feature is disabled. It did not work on all screens and it does not look pretty on some devices.

**Comment by Moostek** [comment]
Well, and will it be possible to bring it back to the Settings where user can allow or disable this? That will eb coolk. I need it, because my phone has some temporarily display issues and rotation is the only option how to resolve this (how to selct number, etc.). Thank you.

**Comment by Goodwy** [comment]
Added auto-rotate in settings.
