### ISSUE TITLE
Source bug

### ISSUE THREAD

**Issue by theLittlePrinceAD** [Goodwy/Dialer#21]
In Dialer I am using just one active Source - @outlook.com. Unfortunately some of the contacts show as if they come from another source @gmail.com (I have this source too - it is my phone Google account, but it is not active). This is not true - they come from @outlook.com, just the info is wrong.
In the Contacts app there is NO error in this regard.

**Comment by Goodwy** [comment]
This app has all sources enabled by default. Try removing the extra source in the filter.

**Comment by Goodwy** [comment]
Does this problem exist in the latest versions of 5.0.0+? We changed the behavior of sources in this update.

**Comment by theLittlePrinceAD** [comment]
Hello,
Checked the situation, unfortunately I do not see a change.
1) If I open Right Contacts (RC) and open a contact - and look at the Contact source - it gives me the correct source (account@ outlook.com)
2) If I open Right Dialer (RD) and open a contact (using the same RC) - and look at the Contact source  - it gives me wrong source of contact - actually it gives two sources - one is the correct ***@***.***) and the second is the Google source ***@***.***) - which is switched off in "Filters" and shouldn't be listed as source.
N.B. Not all contacts show this error - some are showing correct Contact source.

I hope to have helped :)
BR


    On Saturday, February 17, 2024 at 07:36:03 AM GMT+2, Goodwy ***@***.***> wrote: 



Does this problem exist in the latest versions of 5.0.0+? We changed the behavior of sources in this update.

**Comment by Goodwy** [comment]
Is source disabled in both the Daler and Contacts apps?

**Comment by theLittlePrinceAD** [comment]
In both of them I have one and the same source enabled - account @outlook.com.

    On Sunday, February 18, 2024 at 08:43:04 PM GMT+2, Goodwy ***@***.***> wrote:  
 
 


Is source disabled in both the Daler and Contacts apps?

**Comment by Goodwy** [comment]
Fixed on version 5.2.1
