### ISSUE TITLE
IMPROVEMENT: An option to call any number anonymously 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Dialer#22]
Hello, I found one feature I miss in Right Dialer. It will be very nice to have an ability to call the number anonymously (#31#). As I know the general code is "#31# and it is international (isn't it?). Anyway, it will be perfect to have an option to call anonymously from the detail list of the number. For now there are icons "Message", "Call", "Videocall" and "Email". I think that to put there an icon (let's say] "Call (a)" right behind the "Call" icon will be just perfect, OR alternatively it might be made by long press on the "Call" icon. 

Without this feature it is really cumbersome to call anybody with "#31#" prefix. I have to make it manually.. 

In Settings there should be possibly an item to activate/disable this feature and to allow this feature for known countries where this feature is for free. 

Thank you.

**Comment by Moostek** [comment]
Hello, thank you for the implementation of this feature. But as I see, I can manage anon call via #31# only from the "Recent" list. I did not find this context menu feature in "Contacts" and "Favorites". So can you implement this feature also in those two section, please?

**Comment by sphh** [comment]
How would I use this feature? My version is 5.3.0 and I cannot find this feature, not even on the Recent list.

**Comment by sphh** [comment]
Ah, I see. I long pressed the number, tapped the i icon, but it did not occur to me, to long press that i icon. Thanks.

Two ideas:
1. If you press the i icon, the details are shown with the option to call that number. Could the anonymous calling included there? (Maybe configurable?)
2. I have tow SIM cards in my phone and I configured it to be asked for every phone call, which SIM card to use. This would be an obvious place, to include the anonymous calling feature: Use SIM 1, SIM1 (anonymous), SIM2, SIM2 (anonymous). If there is only one SIM card, it would be: SIM1 and SIM1 (anonymous). This obviously should be configurable.

What do you think?

**Comment by Goodwy** [comment]
> Ah, I see. I long pressed the number, tapped the i icon, but it did not occur to me, to long press that i icon. Thanks.
> 
> Two ideas:
> 
> 1. If you press the i icon, the details are shown with the option to call that number. Could the anonymous calling included there? (Maybe configurable?)
> 2. I have tow SIM cards in my phone and I configured it to be asked for every phone call, which SIM card to use. This would be an obvious place, to include the anonymous calling feature: Use SIM 1, SIM1 (anonymous), SIM2, SIM2 (anonymous). If there is only one SIM card, it would be: SIM1 and SIM1 (anonymous). This obviously should be configurable.
> 
> What do you think?

The first item will be in the next version.
The second item does not look very nice, too many buttons.

**Comment by sphh** [comment]
Thanks @Goodwy for considering this (and implementing the first item).

For the second item I would like to suggest the following streamlined call screen:
![Screenshot_20241125-131207_mod2](https://github.com/user-attachments/assets/5b7f9fae-b994-4521-90ef-ec20499c2b10)

The `⋮` opens a menu with the following items:
1. Call the number
2. Call the number anonymously
3. Checkbox with ‘Always use this SIM for calling this number’
4. Checkbox with ‘Always call this number anonymously’

This would also remove the clutter of the screen.

BTW it would be great, if the number to be called were displayed as well!:
![Screenshot_20241125-131207_mod](https://github.com/user-attachments/assets/54887db9-ffb2-4515-b16d-465cdbb5ffdb)
