### ISSUE TITLE
Keypad not working with TalkBack

### ISSUE THREAD

**Issue by DavorV** [Goodwy/Dialer#28]
Hi,
I'm enjoying your dialer app. I was given a hint to give it a try regarding the issues with proximity sensors, and it works.
But...
My dear wife uses it with TalkBack, and there is an issue: with TalkBack on, keypad is not registering any numbers. If TalkBack is turned off, it works as it should. This is very odd.
Expected behaviour with TalkBack would be that numbers are selected as you slide with your finger, and "typed" when you lift your finger.
Thanks

**Comment by Goodwy** [comment]
Will be fixed in the next version.
