### ISSUE TITLE
[Request feature] To be able to make calls from the Contacts tab of the application.

### ISSUE THREAD

**Issue by franco27** [Goodwy/Dialer#34]
Version 5.0.0 and Android 10

Hello,

When I search in the call history, I can call the contact. However, when the contact is not in the call history and I search in the Contacts tab of the application, I cannot call the contact directly because the application does not allow it.

I find this absurd. When I long press on a contact in this tab, I do not have a menu to call this contact. And when I click on a contact, I am redirected to Google's Contacts Manager application.

This should be improved and thank you in advance.

**Comment by Goodwy** [comment]
Hello,
we will add it in the next version. In the latest version 5.1.0 you can set the call action to swipe.

**Comment by Goodwy** [comment]
Will be fixed on version 5.1.1.

**Comment by franco27** [comment]
A big thank you
