### ISSUE TITLE
Having some problem with the proximity sensor...

### ISSUE THREAD

**Issue by VadosG** [Goodwy/Dialer#36]
Greetings.
Thank you for the masterpiece dialer.
I have a (perhaps) atypical request. I noticed that the proximity sensor starts working immediately when there is an incoming call, which is why my screen sometimes turns on and immediately turns off. But I think I know a solution, and I would really like to ask to add the option "**Use the proximity sensor only after answering a call**". I.e. only after answering the call, and not to use before that. I think this would help a lot of people with finicky sensors. By the way, WhatsApp does this - the sensor starts working only after a response.
Thanks in advance, if necessary, I'm ready to test.

**Comment by Goodwy** [comment]
In our app, the sensor is also enabled only after answering an incoming call.

**Comment by VadosG** [comment]
But I checked and it wasn't... For example, in https://f-droid.org/packages/de.wivewa.dialer/ it is.

**Comment by Goodwy** [comment]
Will be fixed on version 5.2.2

**Comment by VadosG** [comment]
Thank you, that's exactly what I wanted!
