### ISSUE TITLE
Right Messages & Right Contacts Integration

### ISSUE THREAD

**Issue by Maxitendo1** [Goodwy/Dialer#39]
Integrating the Right Messages and Right Contacts apps into the Phone app would be good. This would reduce the app clutter, improve the user experience and have a simpler navigation. Also only 100,000s of people downloaded the Messages & Contacts app while the Dialer app was downloaded over 5,000,000 times on the Google Play Store. So that would be another good reason to integrate it. Or maybe creating a separate app, which integrates all of the 3 apps.

https://play.google.com/store/apps/details?id=com.goodwy.dialer

https://play.google.com/store/apps/details?id=com.goodwy.smsmessenger

https://play.google.com/store/apps/details?id=com.goodwy.contacts

**Comment by Goodwy** [comment]
It is still possible to combine Dialer and Contacts, but the Messages application does not combine with Dialer at all. Apps are positioned as a safe replacement for Google apps, so they are separated like Google's. I am against combining them into a super app.
