### ISSUE TITLE
Default contact photos are blurry when inside a call and viewing a contact

### ISSUE THREAD

**Issue by GaucovyAero** [Goodwy/Dialer#41]
Screen: 2400x1080, screen size 485dp
App version is 5.2.3

![Screenshot_20240821-191449_Contacts](https://github.com/user-attachments/assets/db2c97d6-3fa6-41ce-9eb1-f99b26ec619c)

**Comment by Goodwy** [comment]
Thanks, fixed it here and in other apps.

**Comment by GaucovyAero** [comment]
thanks 👍
