### ISSUE TITLE
IMPROVEMENT: An option to control the size of contact icon

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Dialer#43]
Hello, with new updates I noticed the contact icon in **Right Dialer** increased, grew up. I do not use photos for contacts, so big empty circle with one letter looks a bit annoying. Can you implement to Settings an option to choose the size of the icon, i.e. a) original small and b) new bigger one (esp. for those they do not use contact photos). I ask for this option in **Right Contacts** too, please. 

Thank you!

**Comment by Maxitendo1** [comment]
@Moostek There is an option in the settings for your request. You can change the contact icon size in List View -> Contact thumbnails size.![Screenshot_20240827-184051.png](https://github.com/user-attachments/assets/a15e69b8-ca7d-4667-b9c2-2f32b4b756ea)

![Screenshot_20240827-183911.png](https://github.com/user-attachments/assets/c1d7c3c8-7090-46b2-a3f3-9488337c722d)

**Comment by Moostek** [comment]
Thank you for your correction with this setting, I overlooked this one. Ok, it works on the contact icon during the call. BUT it does not work on the icon in the **contact detail** - there is still big icon, both in **Dialer** and **Contacts**. Can you add to this settings also the icon in contact detail, please?

**Comment by Maxitendo1** [comment]
You're welcome and yes, you're right. I just checked it myself. If you go into the contact details the size is still the same even after for example selecting the small size. The problem is that it's only for the list view and not the contact details.

There needs to be an integration into the list setting or a separate setting just for the contact details to change the contact icon size. @Goodwy 

Good job finding this issue!

**Comment by Moostek** [comment]
Hey, I just found that even I set up the small contact icon, I get the middle size one on the call screen too. It worked just for first time, but now the icon is middle size again. So issue is not just on the contact detail screen, but also on the call screen. 

I recommend to integrate both these icon size change under one setting - it is also logical. 

Thank you.

**Comment by Moostek** [comment]
Anyway, the "List view" option for the change of the icon size is NOT what I did mean. This is completely different option, the option to change the size of icons in the contact list. I asked for the option to change the icon sizes in the dialer screen and in the contact detail screen. So my initial demand is valid. In Right Dialer & Contacts apps there is no such option to change the size both in the dialer screen and in the contact detail screen. As stated before, I do not use photos for contacts icons, so big icon with a letter looks pretty annoying. Make the option to change this icon size, please. I recommend to merge the icons of the dialer screen and the contact detail screen into one Setting. 
Thank you.

**Comment by Maxitendo1** [comment]
Please look into this. @Goodwy

**Comment by Maxitendo1** [comment]
All good. I just tagged him with a @.

Like this @Moostek 

Are you writing this by email or something? Maybe that's why you only see the link.

**Comment by Moostek** [comment]
All good, no problem. So I wait for the progress. Thank you.

**Comment by Goodwy** [comment]
Returned the old size in version 5.2.9

**Comment by Moostek** [comment]
Ok, will be this change part of the upcoming update?

**Comment by Maxitendo1** [comment]
Yes, it's fixed now. You can download the apk in the releases. Just Contacts still needs to be updated.

**Comment by Moostek** [comment]
Cool, thanks.
