### ISSUE TITLE
After leaving a call on the lock screen, I'm asked for my fingerprint

### ISSUE THREAD

**Issue by GaucovyAero** [Goodwy/Dialer#44]
After finishing a call that was answered on the lock screen, the app asks for my fingerprint (the lock screen gets dark and the arrow that points to my fingerprint sensor lights up) on the lock screen for no reason. After unlocking my phone when it askes me to, I just get to my home screen like nothing.

Device: Xiaomi Poco F3 8/256
OS: crDroid 10.7 (AOSP Android 14)

**Comment by Goodwy** [comment]
How does the in-house application behave in this situation?

**Comment by GaucovyAero** [comment]
after pressing the red button, it just kicks me to the lock screen without darkening my screen and asking for my fingerprint

**Comment by GaucovyAero** [comment]
the in-house app is the aosp14 dialer app, com.android.dialer version 23.0

**Comment by Goodwy** [comment]
Will be fixed on version 5.2.7
