### ISSUE TITLE
Add default country code if phone is missing country code

### ISSUE THREAD

**Issue by eblis** [Goodwy/Dialer#45]
Sometimes you have a phone number saved without the country code.
If you're roaming in another country and want to dial such a number it may be problematic if the country you're in uses the same format for the numbers as you might dial a local number when you want a number from your default country instead, or you might get an invalid number error message.

It would be nice if you could save a "default country code number" setting somewhere, and if you're roaming the phone app will append the country code to all numbers that do not have a country code already, ensuring you're calling a number from your country of origin (default country).

**Comment by Goodwy** [comment]
To do this, we will need to track your location, and we try not to ask for unnecessary permissions to be more confidential for you.

**Comment by eblis** [comment]
You could ask the user for a default country code and use that. 
Tracking the user through various countries doesn't help, your saved numbers without a country code are probably from your home country, otherwise it doesn't make any sense to have them without the country code as they wouldn't work. 

So the user could opt to configure the default country and if so you can use that. If they want privacy they don't configure any country code
