### ISSUE TITLE
View existing contacts in recents page

### ISSUE THREAD

**Issue by eblis** [Goodwy/Dialer#47]
It would be nice if we could also view the contacts we haven't interacted with in the recents page, when searching for a number.
I usually have the recents page as my default page, when I open the dialer. And I want to search for a name, say "Mamaliga", which I know I have at least one contact with that number, but if I haven't called that contact yet (or I called that contact, but with a different Dialer app) it won't show me any hits for my search, I need to remember to go to Contacts page and search there.

It would be nice if the app also allowed you to search for contacts in the Recents page. Maybe show the Recents hits at the top, then some kind of separator then all the other contacts (excluding the ones already matched in the Recents search) that match the search criteria.

**Comment by Goodwy** [comment]
You can change the tab, the search query will remain and will search already in your contacts.
