### ISSUE TITLE
Add option to call back using the same SIM as you were called on

### ISSUE THREAD

**Issue by eblis** [Goodwy/Dialer#51]
I think an option to call the number back using the same SIM you were called on would be very nice.
I have 2 SIMs in my phone and one number (SIM 1) is configured to be the default.

But sometimes people call me on my second SIM (SIM 2) and maybe I don't pick up in time or I need to call them back, if I click on the number to call it will use SIM 1 (as that is the default), I would prefer if the app could call back using whatever SIM i was called from last.

This would work only if I select a call from the Recents call list so it knows which SIM was used for that call.

I do not like to be asked every time which SIM to use (if I don't select SIM 1 as the default), if I don't select a specific SIM to call with via the top menu it should select the SIM used to call me.

**Comment by Goodwy** [comment]
Implemented.
