### ISSUE TITLE
Call history doesn't show time at 480px screen width

### ISSUE THREAD

**Issue by VladV** [Goodwy/Dialer#55]
I have a phone with 1170х480 display size.
At this resolution I can't see the time of a call, only the date. Please see the screenshot attached.
Tried switching from medium to small font size, it doesn't help.

![Screenshot_20241024-082647](https://github.com/user-attachments/assets/72e33e75-360a-41a0-a14d-0e2b4a9f69a9)

**Comment by Goodwy** [comment]
Will be fixed on version 5.5.4+
