### ISSUE TITLE
Cant access pro features because installed calendar wont get recognized

### ISSUE THREAD

**Issue by MarcK95** [Goodwy/Dialer#61]
The title basically says all. I use a Xiaomi 14 running Android 14.
Accessing pro in the gallery works, but the calendar isnt required there anyway.
Also a quick question: is it planned to add the pro-by-installing-other-apps thing to your other apps? And do i really have to pay for every app individually or is there a bundle option i dont find?

**Comment by Goodwy** [comment]
Where did you install the Calendar app from? What is its package name?

>  is it planned to add the pro-by-installing-other-apps thing to your other apps? 
We haven't made any plans yet.

> And do i really have to pay for every app individually or is there a bundle option i dont find?
There are no bundle options, Google Play doesn't support that.

**Comment by MarcK95** [comment]
Installed everything through Play Store.
The package name of the calendar app is com.goodwy.calendar

**Comment by Goodwy** [comment]
Attach a screenshot of where the calendar is not recognized.

**Comment by Achyuth072** [comment]
Adding on to what OP said, it doesn't work with calendar, it keeps saying get in the dialer app even though I've installed and uninstalled multiple times.
![Screenshot_2024-12-07-17-59-31-46_632533886e7fbe26275c4172e1525055.jpg](https://github.com/user-attachments/assets/60e3d681-f625-4f76-91b4-657100f9f9e5)

![Screenshot_2024-12-07-18-09-29-33_b5a5c5cb02ca09c784c5d88160e2ec24.jpg](https://github.com/user-attachments/assets/0cb42865-8d0c-4250-89c3-d04682a7d583)

**Comment by Goodwy** [comment]
The fix will be in version 6.0.2
