### ISSUE TITLE
DIsabling "Show phone numbers" doesn't hide phone numbers in "Recents" tab

### ISSUE THREAD

**Issue by Rafee-M** [Goodwy/Dialer#66]
As the title says, the "Show phone numbers" doesn't seem to affect the Recents tab while the "Format phone numbers" does. Unsure on whether this is a bug or not.

I feel like having it effect both tabs would be a more cohesive experience

**Comment by Goodwy** [comment]
That's the way it's designed, showing the number affects the contact list and favorites. Number formatting now affects not only lists, maybe the setting should be moved to another section, but I haven't decided yet.

**Comment by Rafee-M** [comment]
Ah okay, got it. Yeah it is more of a subjective choice. Closing it then, thanks!
