### ISSUE TITLE
crashed on MTK devices

### ISSUE THREAD

**Issue by LeOS-GSI** [Goodwy/Dialer#9]
Hi, in my community we have tested the dialer app on several devices running my LeOS-GSI Android 13. 
On qualcomm devices we facing no problems, but on some MTK device the app is crashing.

Umidigi 5pro -> app is crashing at start
Cubot KK2 mini -> 
-doesn't scroll, so R-Z is not visible.
-contacts take multiple seconds to load
-call log not shown
-keeps stopping

Umigidi and Cubot devices are both running LeOS-20 ( Android 13)

on Realme C11 with LeOS-20 and MI11T with stock A13 --- both are MTK devices -- all fine

I hope I can get a log from Umidigi device later

**Comment by LeOS-GSI** [comment]
[Dialer-log.txt](https://github.com/Goodwy/Dialer/files/10825135/Dialer-log.txt)
Here the log from Umidigi Phone

**Comment by LeOS-GSI** [comment]
Here the logcat from Cubot KK2 mini. 
[log (7).txt](https://github.com/Goodwy/Dialer/files/10831890/log.7.txt)

**Comment by Goodwy** [comment]
Should be fixed on version 4+.
